version: '3.8'

services:
  # postgres:
  #   image: postgres:15
  #   container_name: messaging-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: messaging
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   ports:
  #     - "5423:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  redis:
    image: redis:7
    container_name: messaging-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: messaging-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  

volumes:
  postgres-data:
    name: messaging-postgres-data
  dynamodb-data:
    name: messaging-dynamodb-data